### ISSUE TITLE
不能访问了

### ISSUE THREAD

**Issue by mmdjiji** [Saltro/nano#28]
![截图](https://s2.loli.net/2022/12/09/QS2ELYnyJpts93c.png)

如果下线了，能否公开巡礼数据以便规划旅行。或者利用巡礼数据重构一个纯前端的巡礼Wiki

**Comment by Saltro** [comment]
项目已经下线了目前无法访问。巡礼数据主要取自片场app和anime-tourism.jp，如果对数据有需要可以去这两个来源找一下。
